projectId: app-usvSmC29ZXdTHRDFW42z2E
appName: petclinic
description: Sample application
imageURL: http://image.com/image
version: 1.0.0
hostName: example.test
clusterURL: https://kubernetes.default.svc
clusterIPs:
- 192.168.59.103
monitoring: true
microservices:
  petService:
    serviceName: petservice
    avgReplicas: 2
    minReplicas: 1
    maxReplicas: 5
    maxCPU: 200m
    maxMemory: 700Mi
    dockerImage: ashutoshsahoo/spring-boot-kubernetes-mysql:5.0.0
    containerPort: 8080
    envs:
      MYSQL_DATABASE:
        name: MYSQL_DATABASE
        value: petdb
      MYSQL_PASSWORD:
        name: MYSQL_PASSWORD
        value: test123
      MYSQL_ROOT_PASSWORD:
        name: MYSQL_ROOT_PASSWORD
        value: password
      MYSQL_USER:
        name: MYSQL_USER
        value: testuser
      SPRING_DATASOURCE_PASSWORD:
        name: SPRING_DATASOURCE_PASSWORD
        value: dGVzdDEyMw==
      SPRING_DATASOURCE_URL:
        name: SPRING_DATASOURCE_URL
        value: jdbc:mysql://mysql/petdb
      SPRING_DATASOURCE_USERNAME:
        name: SPRING_DATASOURCE_USERNAME
        value: testuser
      SPRING_PROFILES_ACTIVE:
        name: SPRING_PROFILES_ACTIVE
        value: k8s
    serviceEvaluation:
      kubeConfigType:
      - statefulSetBased
evaluationResult:
  language: Java
  database: MySQL
  microservices:
  - petService
