apiVersion: apps/v1
kind: Deployment
metadata:
  name: '{{.Values.microservices.petService.serviceName}}'
  labels:
    app: '{{.Values.microservices.petService.serviceName}}'
spec:
  replicas: 2
  selector:
    matchLabels:
      app: '{{.Values.microservices.petService.serviceName}}'
  template:
    metadata:
      labels:
        app: '{{.Values.microservices.petService.serviceName}}'
    spec:
      containers:
      - name: '{{.Values.microservices.petService.serviceName}}'
        image: '{{.Values.microservices.petService.dockerImage}}'
        ports:
        - containerPort: 8080
        env:
        - name: '{{.Values.microservices.petService.envs.MYSQL_USER.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.MYSQL_USER.name}}'
        - name: '{{.Values.microservices.petService.envs.MYSQL_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.MYSQL_PASSWORD.name}}'
        - name: '{{.Values.microservices.petService.envs.SPRING_PROFILES_ACTIVE.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.SPRING_PROFILES_ACTIVE.name}}'
        - name: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_URL.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_URL.name}}'
        - name: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_USERNAME.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_USERNAME.name}}'
        - name: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.SPRING_DATASOURCE_PASSWORD.name}}'
        - name: '{{.Values.microservices.petService.envs.MYSQL_DATABASE.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.MYSQL_DATABASE.name}}'
        - name: '{{.Values.microservices.petService.envs.MYSQL_ROOT_PASSWORD.name}}'
          valueFrom:
            configMapKeyRef:
              name: '{{.Values.microservices.petService.serviceName}}'
              key: '{{.Values.microservices.petService.envs.MYSQL_ROOT_PASSWORD.name}}'
        resources:
          requests:
            cpu: 100m
            memory: 500Mi
          limits:
            cpu: '{{.Values.microservices.petService.maxCPU}}'
            memory: '{{.Values.microservices.petService.maxMemory}}'
